### ISSUE TITLE
Rebuild dependencies as UMD modules

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs-client#5]
Opening this here, but the changes are at the included libraries instead. Just a note here for now though.

The reason some of the modules are not exporting functions is because the current bundles are meant to be used directly by the browser (which is the default for Webpack).

We instead intend to use these as UMD modules instead, so will need to output two modules for each library -- one the default browser bundle for direct use, and a UMD module.
Webpack can output multiple builds fairly easily, so this isn't a huge change.

I'll try to put up an example first.

**Comment by humitos** [comment]
Yesterday, I figured out how to do this and I was able to use EthicalAd client as a UMD module with this config: https://github.com/readthedocs/ethical-ad-client/pull/148/files#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166fR16

```javascript
    output: {
      libraryTarget: "umd",
```

https://webpack.js.org/configuration/output/#outputlibrarytarget

**Comment by agjohnson** [comment]
Yup that's the option. The work here is to break up the webpack configuration more, and go from outputting a dev/prod set of bundles to a dev/prod set of bundles for each library type.

**Comment by agjohnson** [comment]
Example is here: https://github.com/readthedocs/doc-diff/pull/9

On second thought, it's not necessary to split up most of our modules any more than they are. We likely just want to switch all of them to UMD instead. Also @humitos you do not need the other options you noted on the call.

The EA client sticks out, I think they are using the global/window variable (`window.ethicalads`).

**Comment by humitos** [comment]
We only need to polish the work we already done for EthicalAds and doc-diff only.

`sphinx-hoverxref` is being completely re-written using a different tooltips backend (`tippy.js`, which uses `popper.js` behind the scenes) and the js file from `readthedocs-sphinx-search` that uses the APIv3 was copied and included into this repository because I ended up required too many modifications.

Besides, I don't think it makes sense to continue supporting/maintaining these Sphinx extensions anymore. We should focus on doctool agnostic solutions we are creating and reduce the overhead that the fact of being _an extension_ involves.

**Comment by humitos** [comment]
I'm going to close this because I've just included docdiff into this client in #63 and we have an issue for ethical ads at #6
